# nixpacks.toml - Railway build configuration for WeasyPrint

[phases.setup]
# IMPORTANT: Use aptPkgs (not nixPkgs) so libraries are available at runtime
aptPkgs = [
    "libcairo2",
    "libpango-1.0-0",
    "libpangocairo-1.0-0",
    "libgdk-pixbuf2.0-0",
    "libffi-dev",
    "shared-mime-info"
]
